//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class proyectoEntities : DbContext
    {
        public proyectoEntities()
            : base("name=proyectoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tb_cantidad_cuotas> tb_cantidad_cuotas { get; set; }
        public virtual DbSet<tb_credenciales> tb_credenciales { get; set; }
        public virtual DbSet<tb_cuotas> tb_cuotas { get; set; }
        public virtual DbSet<tb_estados_maritales> tb_estados_maritales { get; set; }
        public virtual DbSet<tb_generos> tb_generos { get; set; }
        public virtual DbSet<tb_intereses> tb_intereses { get; set; }
        public virtual DbSet<tb_pagos> tb_pagos { get; set; }
        public virtual DbSet<tb_prestamos> tb_prestamos { get; set; }
        public virtual DbSet<tb_roles> tb_roles { get; set; }
        public virtual DbSet<tb_tipo_clientes> tb_tipo_clientes { get; set; }
        public virtual DbSet<tb_usuarios> tb_usuarios { get; set; }
        public virtual DbSet<tb_bitacora_prestamos> tb_bitacora_prestamos { get; set; }
    }
}
