//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cuotas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_cuotas()
        {
            this.tb_pagos = new HashSet<tb_pagos>();
        }
    
        public int id_cuota { get; set; }
        public System.DateTime fecha_limite_pago { get; set; }
        public decimal monto { get; set; }
        public string estado { get; set; }
        public int id_prestamo { get; set; }
        public Nullable<int> cuota_num { get; set; }
    
        public virtual tb_prestamos tb_prestamos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pagos> tb_pagos { get; set; }
    }
}
