//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_intereses
    {
        public int id_interes { get; set; }
        public decimal porcentaje_interes { get; set; }
        public int id_tipo_cliente { get; set; }
        public int id_cantidad_cuota { get; set; }
    
        public virtual tb_cantidad_cuotas tb_cantidad_cuotas { get; set; }
        public virtual tb_tipo_clientes tb_tipo_clientes { get; set; }
    }
}
