//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_prestamos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_prestamos()
        {
            this.tb_cuotas = new HashSet<tb_cuotas>();
        }
    
        public int id_prestamo { get; set; }
        public decimal monto_solicitado { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_final { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_cantidad_cuota { get; set; }
        public Nullable<decimal> monto_real { get; set; }
        public string estado { get; set; }
        public string descripcion { get; set; }
        public System.Guid ssma_rowid { get; set; }
    
        public virtual tb_cantidad_cuotas tb_cantidad_cuotas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_cuotas> tb_cuotas { get; set; }
        public virtual tb_usuarios tb_usuarios { get; set; }
        public virtual tb_usuarios tb_usuarios1 { get; set; }
    }
}
