//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pagos
    {
        public int id_pago { get; set; }
        public System.DateTime Fecha_pag { get; set; }
        public Nullable<int> id_cuota { get; set; }
        public string tarjeta_credito { get; set; }
    
        public virtual tb_cuotas tb_cuotas { get; set; }
    }
}
